#!/bin/sh -x

export CLDR_DIR=~/Documents/Development/Playground/cldr/core
CLDR_TOOLS_FOLDER=~/Documents/Development/Playground/cldr/tools/tools
ICU4J_FOLDER=~/Documents/Development/Playground/cldr/icu4j-52_1

MY_CLASSPATH=${CLDR_TOOLS_FOLDER}/java/classes:${ICU4J_FOLDER}/main/tests/framework/out/lib/icu4j-test-framework.jar:${ICU4J_FOLDER}/icu4j.jar:${ICU4J_FOLDER}/main/tests/translit/out/lib/icu4j-translit-tests.jar

MAIN_CLASS=org.unicode.cldr.json.Ldml2JsonConverter

# ./Ldml2JsonConverter -d cldr -t main -r false -l modern
# ./Ldml2JsonConverter -d cldr -t supplemental -r false -l modern
java -cp ${MY_CLASSPATH} ${MAIN_CLASS} $* 